### ISSUE TITLE
Team meeting 3

### ISSUE THREAD

**Issue by genterist** [genterist/whiteWolf#1]

**Comment by genterist** [comment]
+ Team name + Project URL are done.

**Comment by genterist** [comment]
Identified team's focus  : reducing hospical acquired infections

**Comment by mfarve1** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3963198/table/T1/ - list of causes of acquired infections

Stuff I want to know:
How do hospital staff track procedures that prevent infections
- hand washing, disposal of waste, cleaning equipment,. 

How do hospital staff assess high risk patients and does that determine their location within the hospital?
 example - is it protocol to place highly infectious patients next to healthy patients.

**Comment by genterist** [comment]
Question to mentors:
Availability time
Are you able to share some statistics?

**Comment by genterist** [comment]
Letter to potential mentors (an USPHS Captain will help with forwarding):
Audience : senior managers in health institutions accross US

+Introduce our team, our project, missions, etc. 
+Our timeline, expectations for them.
+ Asking to volunteer as group's mentors
+ ....

**Comment by ChristineTzeng** [comment]
Questions:
1. Do hospital staffs have more procedures to perform during infectious diseases break out?
If yes, what's the details? Or just as usual?
2. If people are aware of what happens(diseases) and do follow some procedures(e.g. wash hands more often or use gauze mask when going outside), will that helps to reduce infections? If yes, is there actual data to prove that?

**Comment by genterist** [comment]
@ChristineTzeng and @mfarve1 : 
Matt suggests a team meeting this weekend. I am free on Sat and Sun. Are you availalbe Chrsitine ?
