### ISSUE TITLE
group meeting on Jan. 30 starts from 6 pm in Hunt Library Room 2323

### ISSUE THREAD

**Issue by ChristineTzeng** [genterist/whiteWolf#12]

**Comment by genterist** [comment]
Team,

For this coming 30JAN meeting, I think we should start discussing on how the specifics of our team's software development. I would recommend each of us think about the quickest way to build a concept prototype first (with just the basic features needed to illustrate each of our concepts using the technologies you are most familiar with).

**Comment by genterist** [comment]
Team meeting:
- [x] Discussed general strategies
- [x] Formed backup plan
- [x] Decided on general project development schedule that will be reflected by Milstone 2 tasks.
- [x] Wrap up powerpoint presentations and issue research paper
