### ISSUE TITLE
Announcements - FEB milestone

### ISSUE THREAD

**Issue by genterist** [genterist/whiteWolf#13]
Task Tracking Tool:

Remember Dr. Menzes mentioned Googlers used sticky notes on white boards? We have an equivalence here on GitHub. Please go to Projects > Basic demo prototyping and you will see 3 columns.
You can then create the tasks you are planning to do in the "Todo" column. Please try to be specific and realistic as possible especially when it comes to the time you think you will need to finish a particular task.  When you are working on a certain task, please drag it to the "in-progress" column, and when you're done, drag it to the "finish" column.

This will help everyone in the team keep track of the progress of our project and remind/help each other out if necessary.

**Comment by genterist** [comment]
Team,
Our team's DEVLOG.md was created https://github.com/genterist/whiteWolf/blob/master/DEVLOG.md
Please try to update the file with your activities. Activities are categorized into "Add", "Change" and "Remove". Generally, you can just put any activities under the "Add" section.

Our github also has the "Labs" folder where you can put whatever codes (not directly related to main codes) that you are working on in there (include server side codes, etc). 

Whatever project activities you are working on, I highly recommend you upload the codes of that activities on here. Let's try to do at least 2 commits for each team member per week.

Tam.

**Comment by genterist** [comment]
ATTN >> Recommended practice when working with IBM BlueMix

1- Modify the mobil "screen" that you're supposed to be working on only
2- Log out of Bluemix completely and close all BlueMix windows after you're done (don't leave the same window opened because it may cache old screen settings and when you're back, working on your screen, hit save, you will revert the changes made by others)
3- If you delete or accidentally delete anything from bluemix, please let other members know

Happy coding team ! :)

@ChristineTzeng  @mfarve1

**Comment by genterist** [comment]
ATTN >> IBM Cloud Foundry Outage
There is an issue going on with IBM Cloud Foundry web interface communicating with Cloud Foundry's CLI. The bottom line is you may not be able to control our apps from the IBM Dashboard.
The status of the issue is available at http://ibm.biz/bluemixstatus
.
I would recommend we do something else until it's fixed. (it should be fixed really soon though)

Tam.

**Comment by genterist** [comment]
IBM cloud service console is back to normal as of late yesterday.

**Comment by mfarve1** [comment]
Team,

I wanted to give you a heads up that I will not be in class today, I have a meeting at 4pm. I am still working on the AutoRefresh and having some minor issues.  Tam I was able to share my iphone screen with my mac so that is do able, but can you please bring a charging cord (USB) for your android phone for tomorrows sessions so I can test screen sharing with it.  

Lastly, what time do you want to meet tomorrow morning?  On Tuesday we said 930, is that still correct?

Best,
Matt

**Comment by genterist** [comment]
Matt,
I've just sent out an email with further details. See you tomorrow.
