### ISSUE TITLE
Conduct research on problems in daily Hospital Operations

### ISSUE THREAD

**Issue by genterist** [genterist/whiteWolf#2]

**Comment by genterist** [comment]
According to:

**Critical Issues in Healthcare Environments**
By Uriel Cohen, D.Arch, and David Allison, AIA
Published by The Center for Health Design, 2009 and sponsored by Bayer Material Science, Herman Miller, and Frank Zilm Inc.

Top issues in Hospital Settings
![screen shot 2017-01-18 at 12 17 28 pm](https://cloud.githubusercontent.com/assets/21042389/22074983/42f37d5e-dd78-11e6-84f8-244336be3d9c.png)

Top issues in Ambulatory Settings
![screen shot 2017-01-18 at 12 20 12 pm](https://cloud.githubusercontent.com/assets/21042389/22075054/7fbb0b9e-dd78-11e6-9ca4-64be1b855d4a.png)

Top issues in Longterm Care Settings
![screen shot 2017-01-18 at 12 20 53 pm](https://cloud.githubusercontent.com/assets/21042389/22075091/a456c704-dd78-11e6-97bf-ac516a6c1ae9.png)

Single most critical problems
![screen shot 2017-01-18 at 12 22 24 pm](https://cloud.githubusercontent.com/assets/21042389/22075141/cca97ad0-dd78-11e6-8f35-242c5e56971e.png)

![screen shot 2017-01-18 at 12 23 16 pm](https://cloud.githubusercontent.com/assets/21042389/22075170/eaf61c46-dd78-11e6-8d50-3f37f55efa60.png)

Comparison of Serious Problems across all settings
![screen shot 2017-01-18 at 12 24 43 pm](https://cloud.githubusercontent.com/assets/21042389/22075226/220153a4-dd79-11e6-8ebe-d168cf0f0418.png)

![screen shot 2017-01-18 at 12 26 10 pm](https://cloud.githubusercontent.com/assets/21042389/22075262/53cae6e8-dd79-11e6-9e15-78234bc6d64b.png)

**Comment by genterist** [comment]
From:
Wachter, Robert M. Understanding patient safety. New York: McGraw-Hill Medical, 2008.

THE ISSUE LANDSCAPE:
+ According to Harvard Medical Practice Study (IOM : To Err is Human: Building a Safer Health System), in late 1980s, there were about 44,000 to 98,000 Americans die each year from medical errors which equals to one jumbo jet crashing each and everyday in the US.
+ Attempted strategies : improved ratios of providers to "customers" / Decrease provider fatigue / Improve teamwork and communication / Use of simulators / Executive walk rounds / Bar coding
+ Famous cases : Betsy Lehman died of a chemotherapy overdose (1994) / Willie King has the wrong leg amputated (1995) / Two healthy young volunteers (Jesse Gelsinger and Ellen Roche) died while participating in research studies (1999 and 2001) / 18-month old Josie King died of dehydration in hospital (2001) / Jesica Santillan died after receiving a heart-lung transplant of the wrong blood type (2003) >> all happened at famous hospitals. Ref Page 5 or internet.
+ Issues with error reporting : Few doctors report errors officially. Timing of reports may not correspond to actual rate of error. Some tools are expensive. Some tools are subjected to bias
+ Observation of patient care method : potentially accurate and precise. Provides data otherwise unavailable. Detects more active errors than other methods. CONS: difficult to train reliable observers, potential concerns about confidentiality. Possible to overwhelemed with information. Time consuming and expensive
+ Slips V.S. Mistakes : Slips represent the greater threat because most of the tasks are automatic with little interactions with "customers" >> prevent by building in redundancies with standardization and simplification
+ A large healthcare system will have to handle the data 5 times greater than NASDAQ (on daily basis)
+ Tracking of information is a huge challenge consider the balance of privacy and different institutions a person go to over a long period of time
+ The issue of presenting only relevant information to a particular case

**Comment by tweakprime** [comment]
Thank you
