### ISSUE TITLE
[Christine] researching and implementing andoid push notifications / server set up(php)

### ISSUE THREAD

**Issue by ChristineTzeng** [genterist/whiteWolf#22]

**Comment by ChristineTzeng** [comment]
Hey,
The 'Apple Push Notification' feature is only available to users enrolled in Apple Developer Program.
And the Apple Developer Program Enrollment requires abt $100

**Comment by genterist** [comment]
We can demo on android platform Christine. I mentioned Google dev acc last time we talked.

**Comment by ChristineTzeng** [comment]
Actually for ios and android we only have 2 possible dev acc to get.
Are we gonna demo with both ios and android on the demo day?

**Comment by genterist** [comment]
We can demo the push on android if the 99 dollar iOS dev acc is required for push on iOS
