### ISSUE TITLE
[Matt - 17FEB] Auto Refresh, No Finger

### ISSUE THREAD

**Issue by mfarve1** [genterist/whiteWolf#25]

**Comment by mfarve1** [comment]
Tam,

I am trying to test if my refresh code works but the simulator is now asking me for an email and password to get into the app.  Can you unlock that function of the app?  

Thanks,
Matt

**Comment by genterist** [comment]
Sorry about that Matt. It's removed.

**Comment by mfarve1** [comment]
Thanks Tam,

For some reason the simulator is not connecting to the server now. I will try again tomorrow morning. 

Matt

**Comment by mfarve1** [comment]
Tam,

Any thoughts on why the simulator is not connecting to the demo server? In xcode all I am getting is "whitewolfdemo[somenumbers] Reachability: Reachable via WiFi"  before I could see that it would connect to the server now its not.  

Let me know what you think when you get a chance. 

Matt

**Comment by genterist** [comment]
Matt,

Try export code in blue mix, download it, run the pod file and see if it works.
IBM is moving its mobile building console to a separate company (buildup.io). If you have issues with iOS, you can work on other tasks of our project and we'll talk more on the mobile side tomorrow.

Tam
