### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by genterist** [genterist/whiteWolf#7]
Please use this instead of gmail

**Comment by genterist** [comment]
I added the Prof. and the TA to our GitHub. I also added more files and issues to our project. Issues will be organized by mileStone so when you go to Issues >> MileStone, you will see a progress bar on how far we are 'till the finish. I think just like the way we do in our group meeting, let's just fill up the "issues" with each of us own logs about what each of us has done. I'll put mine in tomorrow. I am still new with GitHub issues so please please correct me or let all of us know if you have different/better ideas.

**Comment by mfarve1** [comment]
Tam,

Nice work on the organization, I have time scheduled tomorrow to conduct research and formulate possible survey questions.

**Comment by genterist** [comment]
Team,

Do you think we need to have additional face to face meetings this week and next week (basically we only have 9 days to wrap up our first milestone 1 (Jan Milestone). I am free on Sat and Sun this week.
I will post more stuffs that I've been working on to our GitHub including the contents that I've sent to you over the email or discussed in previous meetings. I can't wait to see yours too. I guess the more stuffs we put on here, the faster we can construct our slides (and easier to finish the April Milestone)

Christine, would you help us by creating a new issue for our next group meeting and include the room info there! Thanks Christine.

Tam.

**Comment by mfarve1** [comment]
it may be helpful to have one this weekend, We need to layout a structure for our presentation and the paper.  After that we just need to collect the data and user observations.

**Comment by genterist** [comment]
Team,

Please go to https://ncsu.onthehub.com/WebStore/Welcome.aspx and get your IBM Bluemix promo code and register for an IBM Bluemix account at https://console.ng.bluemix.net/
In our team meeting, I'll show you how to quickly deploy an mobil app (with database, authentication, etc). I think it will help you save lots of time later on in Feb.

Tam

**Comment by genterist** [comment]
Further resources for writing our paper:
+ How to write good Literature Review: 
https://www.lib.ncsu.edu/tutorials/litreview/
+ Writing assignment resources
https://www.lib.ncsu.edu/guides/WritingResources/assignments
+ Reference/citation management tools
https://www.lib.ncsu.edu/guides/refworks
@ChristineTzeng @mfarve1

**Comment by genterist** [comment]
I added a section named "Proposed solutions" to our paper. I think it is crucial that we talk about our solutions after we identified all the issues from user studies and literature reviews.
Happy Writing folks :)

@mfarve1 @ChristineTzeng

**Comment by mfarve1** [comment]
I disagree with adding proposed solutions, the purpose of the paper is to identify a problem and discuss how its being solved today with surveys, data, and lit reviews. As far as I know, none of the examples given include their proposed solutions.  I realize that it wouldn't hurt to add but realistically we could get feed back from the class after our presentation and find out our proposed solutions right now are garbage.  

Just my thoughts.

**Comment by genterist** [comment]
@mfarve1 
We do not have to go into details of our specific solution but we have to express what we think is lacking in existing solutions and how our team can add more values. The sample papers did exactly that and let me show it.

Clipit paper:
"Finally we propose a project wherein we will be building a fully featured Eclipse IDE plug-in, Clippit, which will provide Java programmers with a visual clipboard manager ..."

SimpleShot paper:
" We are looking at an innovative approach of solving this problem by reducing clutter and cumbersome task of taking screen-shots, cutting and sharing"

My point is to emphasize more on are we able to realize the problems and (more importantly), where do we stand on the problem solving (considering there could be many ways to solve the problem) . What is the link between what we found and what we will do next? Also, Literature Review is more than just summarizing the paper and it's clearly emphasized in here https://www.lib.ncsu.edu/tutorials/litreview/

It is also important to note that the Professor wants 5+ pages on the paper.

By the way, I think all of our ideas are great. Survey results agreed with it. This paper can be a great place to sell more on our ideas.

**Comment by mfarve1** [comment]
Sounds good. We can discuss tonight.

**Comment by genterist** [comment]
Finished Mile stone 1 today. All milestone 1 issues are closed.
