### ISSUE TITLE
Team meeting 4

### ISSUE THREAD

**Issue by ChristineTzeng** [genterist/whiteWolf#8]
Room 2325 in Hunt Library on Jan. 21 from 1 pm to 3 pm.

**Comment by ChristineTzeng** [comment]
- try to contact NCSU health center to acquire some professional opinions/suggestions/data
- draft questionnaire(10 quesitons)
    - collect data with Amazon mechanical Turk but only give reward once a participant pass the first question
- draft slides
- have a draft report by Tuesday

**Comment by ChristineTzeng** [comment]
My another question for the questionnaire is- What will you(people or hospital staffs) do during an outbreak to prevent infections? By what percentage do you think those actions prevent you(or others) from infection?

**Comment by mfarve1** [comment]
Does your facility have a surveillance program to prevent HAI? 
(Surveillance Program - Ongoing, systematic collection, analysis, and interpretation of health data essential to the planning, implementation, and evaluation of public health practice to prevent or reduce HAI)
-Yes/No

If yes, Is the the surveillance Program effective at reducing HAI?
-Yes/No

How is the data for the surveillance program entered into the system?
-I dont know
-Nurses or equivalent staff personnel manually enter the data
-Healthcare administrators enter the data manually
-The data is automatically entered into the surveillance system

Rank the following issues regarding the a surveillance system?
-It takes too much time to keep the system updated with correct data
-lack of training on the surveillance system
-difficulty understanding the surveillance system
-Surveillance system is not accurate

**Comment by genterist** [comment]
Alright. Thanks team. I am forming the survey now. I should be able to send out the survey to you within 30 mins from now. Please make sure you check it and if there is no objection, it will go live 30 minutes after you receive the survey in the email.
10:21pm

**Comment by genterist** [comment]
Our survey is LIVE. We use Mechanical Turk _ Qualtrics. 
For documentation purposes, contents of survey will be posted later on when the campaign is over.
