### ISSUE TITLE
Team meeting 5(weekly)

### ISSUE THREAD

**Issue by ChristineTzeng** [genterist/whiteWolf#9]
- [x] buy pizza
- [x] book room

Room 2323 in Hunt Library on Jan. 24 from 3 pm to 4:30 pm

**Comment by mfarve1** [comment]
Paper 
Abstract - Matt
Intro - Matt
Stats about HAI - Christine
Survey - Tam
Lit Review - Matt, Tam, Christine
Conclusion - Matt

**Comment by timm** [comment]
good organization
